package com.github.tshion.mktools_android.webview_builder.aliases

internal typealias MktBiConsumer<T, U> = (T, U) -> Unit
internal typealias MktBiFunction<T, U, R> = (T, U) -> R
internal typealias MktBinaryOperator<T> = (T, T) -> T
internal typealias MktBiPredicate<T, U> = (T, U) -> Boolean
internal typealias MktBooleanSupplier = () -> Boolean
internal typealias MktConsumer<T> = (T) -> Unit
internal typealias MktDoubleBinaryOperator = (Double, Double) -> Double
internal typealias MktDoubleConsumer = (Double) -> Unit
internal typealias MktDoubleFunction<R> = (Double) -> R
internal typealias MktDoublePredicate = (Double) -> Boolean
internal typealias MktDoubleSupplier = () -> Double
internal typealias MktDoubleToIntFunction = (Double) -> Int
internal typealias MktDoubleToLongFunction = (Double) -> Long
internal typealias MktDoubleUnaryOperator = (Double) -> Double
internal typealias MktFunction<T, R> = (T) -> R
internal typealias MktIntBinaryOperator = (Int, Int) -> Int
internal typealias MktIntConsumer = (Int) -> Unit
internal typealias MktIntFunction<R> = (Int) -> R
internal typealias MktIntPredicate = (Int) -> Boolean
internal typealias MktIntSupplier = () -> Int
internal typealias MktIntToDoubleFunction = (Int) -> Double
internal typealias MktIntToLongFunction = (Int) -> Long
internal typealias MktIntUnaryOperator = (Int) -> (Int)
internal typealias MktLongBinaryOperator = (Long, Long) -> Long
internal typealias MktLongConsumer = (Long) -> Unit
internal typealias MktLongFunction<R> = (Long) -> R
internal typealias MktLongPredicate = (Long) -> Boolean
internal typealias MktLongSupplier = () -> Long
internal typealias MktLongToDoubleFunction = (Long) -> Double
internal typealias MktLongToIntFunction = (Long) -> Int
internal typealias MktLongUnaryOperator = (Long, Long) -> Long
internal typealias MktObjDoubleConsumer<T> = (T, Double) -> Unit
internal typealias MktObjIntConsumer<T> = (T, Int) -> Unit
internal typealias MktObjLongConsumer<T> = (T, Long) -> Unit
internal typealias MktPredicate<T> = (T) -> Boolean
internal typealias MktRunnable = () -> Unit
internal typealias MktSupplier<R> = () -> R
internal typealias MktToDoubleBiFunction<T, U> = (T, U) -> Double
internal typealias MktToDoubleFunction<T> = (T) -> Double
internal typealias MktToIntBiFunction<T, U> = (T, U) -> Int
internal typealias MktToIntFunction<T> = (T) -> Int
internal typealias MktToLongBiFunction<T, U> = (T, U) -> Long
internal typealias MktToLongFunction<T> = (T) -> Long
internal typealias MktUnaryOperator<T> = (T, T) -> T
