name: Update Git Tag

on:
  schedule:
    - cron: '0 19 * * *' # 4am JST
  workflow_dispatch:

jobs:
  add_git_tag:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Setup git settings
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - name: Do update
        run: make git-update-tag
